alias: Advent ljusstakar av/på vid soluppgång/solnedgång
mode: single
trigger:
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunset
condition: []
action:
  - if:
      - condition: template
        value_template: '{{ trigger.event == "sunrise" }}'
    then:
      - type: turn_off
        device_id: 5d033409a6b4e768dde217e74466c186
        entity_id: switch.uttag_1
        domain: switch
    else:
      - type: turn_on
        device_id: 5d033409a6b4e768dde217e74466c186
        entity_id: switch.uttag_1
        domain: switch
