- alias: "Tänd/Släck ljusstake"
  id: "dae7c422-03ff-4ae6-a06d-65e4907880e1"
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:15:00"
    - platform: sun
      event: sunrise
      offset: "+00:15:00"
  action:
    - service: "switch.turn_{{'on' if trigger.event == 'sunset' else 'off'}}"
      entity_id: switch.uttag_1
