---
alias: "push HA configuration to GitHub repo"

id: l1k3
trigger:
# Everyday at 23:23:23 time
  - platform: time
    at: "23:23:23"
action:
- data:
    addon: a0d7b954_ssh
    input: /root/ha_gitpush.sh
  service: hassio.addon_stdin
