---
alias: "Telegram bot turn on lamp"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: "/lamp-on"
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.house_mode_sleep
