---
# DSMR Smart Bridge (Slimme brug)
#
# This is a DSMR bridge for the P1 port of my Dutch smart meter.
# It is a pre-assemled device from Marcel Zuidwijk, which I can
# highly recommend.
#
# https://www.zuidwijk.com
#
# This is my version of the configuration, bridge the DSMR serial
# on the network, allowing DSMR capable software to connect with it.
# Connect to it on port 6638.
#
# At the same time, it exposes ESPHome sensors with information on
# the device itself.
#
substitutions:
  label: none
  slug: dsmr_bridge
  name: DSMR Bridge
  description: Bridges a DSMR/P1 port to the network using ESPHome.
  api_password: !secret esphome_dsmr_bridge_api_password
  ota_password: !secret esphome_dsmr_bridge_ota_password

packages:
  <<: !include_dir_named common
  board: !include boards/wemos_d1_mini.yaml
  bridge: !include components/streaming_server.yaml

uart:
  baud_rate: 115200
  rx_pin: D7
