---
# Doorbell
#
# This is my old/original wired doorbell,
# which I converted for just 2$!
#
# I've written an extensive blog post
# on how I did it:
# https://frenck.link/doorbell
#
substitutions:
  label: esp19
  slug: outside_doorbell
  name: Outside Doorbell
  description: Made my old fashioned doorbell smart!
  api_password: !secret esphome_outside_doorbell_api_password
  ota_password: !secret esphome_outside_doorbell_ota_password

packages:
  <<: !include_dir_named common
  board: !include boards/esp01s.yaml

globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: "true"

switch:
  - platform: gpio
    id: relay
    inverted: true
    pin: GPIO0

  - platform: template
    name: "${name} Chime"
    id: chime_switch
    icon: "mdi:alarm-bell"
    restore_state: false
    turn_on_action:
      - globals.set:
          id: chime
          value: "true"
    turn_off_action:
      - globals.set:
          id: chime
          value: "false"
    lambda: |-
      return id(chime);

# This interval shuts off the
# doorbell if it pushed for more
# then 1.5-2.0 seconds.
interval:
  - interval: 500ms
    then:
      - if:
          condition:
            for:
              time: 1.5s
              condition:
                - binary_sensor.is_on: push_button
                - switch.is_on: relay
          then:
            - switch.turn_off: relay

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    id: push_button
    name: "${name}"
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      then:
        if:
          condition:
            - switch.is_on: chime_switch
          then:
            - switch.turn_on: relay
    on_release:
      - switch.turn_off: relay
